name: angular package
on: [push]
jobs:
  build-angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Angular v16
        uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
      - name: Install dependencies
        run: npm ci
        working-directory: fastTyping-Client
      - name: Build
        run: npm run build --if-present
        working-directory: fastTyping-Client
